#============================================================================
# WebServer
#============================================================================
server:
  port: 8080
  servlet:
    context-path: /
    application-display-name: coco
  compression:
    enabled: true

#============================================================================
# Spring
#============================================================================
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  cache:
    type: ehcache
  datasource:
    url: jdbc:sqlite:./Coco.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
    sql-script-encoding: UTF-8
    continue-on-error: false
    schema:
      - classpath:sqls/0.0.1/schema.sql
#    data:
#      - classpath:sqls/0.0.1/data.sql
    initialization-mode: always
    hikari:
      minimum-idle: 10
      maximum-pool-size: 15
      idle-timeout: 60000

#============================================================================
# Mybatis
#============================================================================
mybatis:
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  type-aliases-package: com.github.coco.entity

#============================================================================
# Socket.IO
#============================================================================
socketio:
  host: 0.0.0.0
  port: 9099
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
  # 设置http交互最大内容长度
  maxHttpContentLength: 1048576
  # socket连接数大小（如只监听一个端口boss线程组为1即可）
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 6000000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000

#============================================================================
# Coco
#============================================================================
coco:
  sync-data:
    stack:
      enable: true
      # 应用栈数据同步时间间隔（默认30秒）
      interval: 30000
    endpoint:
      enable: true
      # 服务终端数据同步时间间隔（默认30秒）
      interval: 30000